import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import Image from "next/image";
import pic from "../../public/images/fallingIntoYourSmile.webp"
import CardComponent from "@/components/CardComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{position: "relative", background: "#561C24"}}>  
        {/* <Image src={pic} alt="image" className="absolute -z-10  w-full object-cover h-screen" />
        <div className="absolute w-full h-[100vh] bg-black -z-10 opacity-60 "></div> */}
        <NavbarComponent />
        {children}
        </body>
    </html>
  );
}
