import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import Image from "next/image";
import pic from "../../public/images/fallingIntoYourSmile.webp"
import CardComponent from "@/components/CardComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{position: "relative", background: "#561C24"}}>
        <NavbarComponent />
        {children}
        </body>
    </html>
  );
}
